const products = [
    {
        _id: "1",
        name: "Aipods Wireless Bluetooth",
        image: "/images/airpods.jpg",
        description: "Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working.",
        brand: "Apple",
        category: "Electronics",
        price: 89.99,
        countInStock: 0,
        rating: 4.5,
        numReviews: 4,
    },
       {
        _id: "2",
        name: "Alexa music player boom",
        image: "/images/alexa.jpg",
        description: "This allows us play music like crazy. so, what are you gon' do??? ",
        brand: "Amazon",
        category: "Electronics",
        price: "56.89",
        countInStock: 6,
        rating: 4.2,
        numReviews: 7,
    },
           {
        _id: "3",
        name: "Cannon E045 BOD Camera",
        image: "/images/camera.jpg",
        description: "Nikon 200mp camera",
        brand: "Nikon",
        category: "Camera",
        price: 778.45,
        countInStock: 2,
        rating: 4.7,
        numReviews: 9,
    },
       {
        _id: "4",
        name: "Logitech Gseries Gaming Mouse",
        image: "/images/mouse.jpg",
        description: "Wireless mouse",
        category: "Computing",
        price: 23.65,
        countInStock: 95,
        rating: 3.8,
        numReviews: 12,
    },
       {
        _id: "5",
        name: "Iphone pro max 256GB",
        image: "/images/phone.jpg",
        description: "Iphone 11 max pro",
        brand: "Iphone, Apple Inc",
        category: "Phones",
        price: 768.99,
        countInStock: 56,
        rating: 2.1,
        numReviews: 455,
    },
       {
        _id: "6",
        name: "Sony PlayStation 4 pro white",
        image: "/images/playstation.jpg",
        description: "PS 5 pro",
        brand: "Play Station",
        category: "Gaming",
        price: 1168.99,
        countInStock: 26,
        rating: 4.1,
        numReviews: 88,
    }
]

export default products